
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BRACE FOR ID INCREMENT INT NUM OP PAREN PLUS PRINT SEMICOLON STRINGprograma : buclebucle : FOR PAREN declaracion SEMICOLON condicion SEMICOLON incremento PAREN BRACE cuerpo BRACEdeclaracion : INT ID OP NUMcondicion : ID OP NUMincremento : ID INCREMENTcuerpo : PRINT PAREN STRING PLUS ID PAREN SEMICOLON'
    
_lr_action_items = {'FOR':([0,],[3,]),'$end':([1,2,23,],[0,-1,-2,]),'PAREN':([3,15,19,22,27,],[4,18,-5,24,28,]),'INT':([4,],[6,]),'SEMICOLON':([5,9,14,17,28,],[7,12,-3,-4,29,]),'ID':([6,7,12,26,],[8,10,16,27,]),'OP':([8,10,],[11,13,]),'NUM':([11,13,],[14,17,]),'INCREMENT':([16,],[19,]),'BRACE':([18,21,29,],[20,23,-6,]),'PRINT':([20,],[22,]),'STRING':([24,],[25,]),'PLUS':([25,],[26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'bucle':([0,],[2,]),'declaracion':([4,],[5,]),'condicion':([7,],[9,]),'incremento':([12,],[15,]),'cuerpo':([20,],[21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> bucle','programa',1,'p_programa','parser.py',5),
  ('bucle -> FOR PAREN declaracion SEMICOLON condicion SEMICOLON incremento PAREN BRACE cuerpo BRACE','bucle',11,'p_bucle','parser.py',9),
  ('declaracion -> INT ID OP NUM','declaracion',4,'p_declaracion','parser.py',13),
  ('condicion -> ID OP NUM','condicion',3,'p_condicion','parser.py',17),
  ('incremento -> ID INCREMENT','incremento',2,'p_incremento','parser.py',21),
  ('cuerpo -> PRINT PAREN STRING PLUS ID PAREN SEMICOLON','cuerpo',7,'p_cuerpo','parser.py',25),
]
